### ISSUE TITLE
Context not working with fastdom-promised?

### ISSUE THREAD

**Issue by Dylan-Chapman** [wilsonpage/fastdom#81]
I noticed some weird inconsistent behavior between fastdom and fastdom-promised earlier.

```javascript
var ctx = { test: "test" };

fastdom.measure( function() {
    console.log( this ); // => outputs { test: "test" }
}, ctx );

fastdomPromised.measure( function() {
    console.log( this ); // => outputs the window object
}, ctx );
```

Is this intended behavior? Is this not a way in which context is supposed to be used?

**Comment by wilsonpage** [comment]
Ah yes, I think this is a bug. The bug is [here](https://github.com/wilsonpage/fastdom/blob/master/extensions/fastdom-promised.js#L63)

`fn` should be called like: `fn.call(ctx)`.

Alternatively for a quickfix you can use either:

- `fastdomPromised.measure(() => ... );`
- `fastdomPromised.measure(fn.bind(ctx));`

**Comment by Dylan-Chapman** [comment]
Yep, you were right! ```fn.call(ctx)``` on that line does the trick.

**Comment by wilsonpage** [comment]
Could you send a PR? :)
